name: Build 

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Vendor
      run: go mod tidy; go mod vendor
    - name: Test
      run: go test -v ./...
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: splat-bot
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
