# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: merge

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: splat-bot
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/ocp-splat
        username: ocp-splat+splat_team_push
        password: ${{ secrets.REGISTRY_PASSWORD }}          
