name: Label Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approved and LGTM labels
        uses: actions/github-script@v5
        with:
          script: |
            const { context } = require("@actions/github");
            const pullRequest = context.payload.pull_request;
            const labels = pullRequest.labels.map(label => label.name);

            const hasApprovedLabel = labels.includes('approved');
            const hasLgtmLabel = labels.includes('LGTM');

            if (!hasApprovedLabel || !hasLgtmLabel) {
              core.setFailed('PR must have both "approved" and "LGTM" labels before merging');
            }
